### ISSUE TITLE
Doesn't seem to be working :(

### ISSUE THREAD

**Issue by Lerber11** [LCruel/tanks_for_bob_1.0.0#2]
When I start it up it says:
Error
Filename of mod/users/name/library/applicationSupport/factorio/mods/tanks_for_bob-1.3.0.zip doesn't match the expected tanks_for_bob_1.2.0.zip(case sensitive!)

**Comment by LCruel** [comment]
```
                                                                                  Hmm I thought this was resolved.Did you use zip file in the release or did you download on the project page?Regards,LCruel                                                                                                                                                                                                                                                                                                                                        Verzonden vanaf mijn BlackBerry 10-smartphone.                                                                                                                                                                                                                Van: Lerber11Verzonden: zondag 27 maart 2016 08:13Aan: LCruel/tanks_for_bobBeantwoorden: LCruel/tanks_for_bobOnderwerp: [tanks_for_bob] Doesn't seem to be working :( (#2)When I start it up it says:
```

Error
Filename of mod/users/name/library/applicationSupport/factorio/mods/tanks_for_bob-1.3.0.zip doesn't match the expected tanks_for_bob_1.2.0.zip(case sensitive!)

—You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub

**Comment by Lerber11** [comment]
I used the zip file in the release

**Comment by LCruel** [comment]
I am looking at the release files from 1.3.0 and I cannot replicate the error.

Can you give me the direct URL you are downloading from. (In firefox Right mouse button copy URL)

**Comment by LCruel** [comment]
I think I found the link, it was the one at "http://www.factoriomods.com/mods/tanks-for-bob". 

Can you try and see if it works now?

**Comment by Lerber11** [comment]
It still doesn't seem to work

**Comment by LCruel** [comment]
Hmm, I really like to know the URL you are downloading from. 

I really want to help you out, but for me for some reason it works so I cannot replicate what is going wrong to fix it.

**Comment by Lerber11** [comment]
I tried the one from your link but im gonna try to reinstall factorio and download it again to see if anything changes

**Comment by Lerber11** [comment]
Reinstalling didn't seem to help. 
Maybe is it because I'm on a mac?

**Comment by LCruel** [comment]
I also did a reinstall and it seems the mistake was on my side after all. 

I updated the release to 1.3.2 if you download using this link: https://github.com/LCruel/tanks_for_bob/releases/download/1.3.2/tanks_for_bob_1.3.2.zip it should work.

Let me know if it works, and thank you for teaching me some new stuff. I did not know the game could load zip files.

**Comment by Lerber11** [comment]
It works thanks for helping me :D

**Comment by LCruel** [comment]
fixed
